# cadvisor-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    name: cadvisor
  ports:
  - port: 8080
    targetPort: 8080